version: "3"

services:
    app:
        image: notifications-service
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            ./.env
        ports:
           - "13002:3002"